Fix for Bisa/factorio-init#194: Use factorio api for latest-releases
Bisa/factorio-init pull request #196
Opened 2022-04-09 23:58 UTC by Legrems

2022-04-09 23:59 UTC, Legrems commented on factorio
> +    filename="factorio_headless_x64_${version}.tar.xz"
I'm using this to keep the same filename as the script uses currently.

2022-04-14 20:28 UTC, tmzasz commented
theres 2 methods that do not require the user to install new software nor do they require a large change to the check core.

Method 1: grep + awk
curl -LIs https://www.factorio.com/get-download/stable/headless/linux64 | grep Location | awk -F "?" '{print $1}' | awk -F "/" '{print $NF}' | awk -F "_" '{print $4}' | awk -F ".tar" '{print $1}'

Returns something like this as of today : 1.1.57

Method 2: grep + awk on new API site above

to get experimental
curl -s https://factorio.com/api/latest-releases | awk -F ":" '{print $5 $9}' | awk -F "\"" '{print $2}'
outputs 1.1.57
stable
curl -s https://factorio.com/api/latest-releases | awk -F ":" '{print $5 $9}' | awk -F "\"" '{print $6}'
outputs 1.1.57

both methods are simpler and do not force the user to install/rely on more external software

2022-04-14 20:41 UTC, tmzasz requested changes
use grep + awk or just awk even and do not require the user to install more software just to handle json

2022-04-21 13:44 UTC, Legrems commented
> use grep + awk or just awk even and do not require the user to install more software just to handle json
> 
> there's 2 methods that do not require the user to install new software nor do they require a large change to the check core.
> ### Method 1: grep + awk
> 
> _curl -LIs https://www.factorio.com/get-download/stable/headless/linux64 | grep Location | awk -F "?" '{print $1}' | awk -F "/" '{print $NF}' | awk -F "_" '{print $4}' | awk -F ".tar" '{print $1}'_
> 
> Returns something like this as of today : 1.1.57
> 
> **to get the file name you can do this** _curl -LIs https://www.factorio.com/get-download/stable/headless/linux64 | grep Location | awk -F "?" '{print $1}' | awk -F "/" '{print $NF}'_
> 
> which returns this factorio_headless_x64_1.1.57.tar.xz
> ### Method 2: awk on new API site
> 
> **to get experimental** _curl -s https://factorio.com/api/latest-releases | awk -F ":" '{print $5 $9}' | awk -F """ '{print $2}'_
> 
> outputs 1.1.57
> 
> **to get stable** _curl -s https://factorio.com/api/latest-releases | awk -F ":" '{print $5 $9}' | awk -F """ '{print $6}'_
> 
> outputs 1.1.57
> 
> both methods are simpler and do not force the user to install/rely on more external software
> 
> for Method 2 this is the sample raw output that awk works on {"experimental":{"alpha":"1.1.57","demo":"1.1.57","headless":"1.1.57"},"stable":{"alpha":"1.1.57","demo":"1.1.57","headless":"1.1.57"}} what its doing is breaking down the response first by : parts and then by a " and then returning the numbered column
> 
> the benefit is that any system capable of running a factorio server should also have awk/grep installed by default as they are core POSIX functions

The awk method is not robust to any changes made to the latest releases API.

The advantage of jq (which is by the way super light and you should consider using this for parsing json) is that you rely on key from the json instead of arbitrary number of ":".

Any server capable of running factorio is also capable of having jq installed, since it has no runtime dependencies.

2022-04-21 16:55 UTC, tmzasz commented
the advantage of awk is still 1 less software to install. There is no need to keep installing more and more packages to do something the os is already capable of doing by default. Less complexity is always better than more.

2022-04-28 18:56 UTC, llann commented
I don't understand that "fear" to install such a small lib on a system knowing that we install Factorio and everything that goes with it. Using this makes the code more readable and more resistant to changes that the dev. may do in the API.

2022-04-28 19:19 UTC, tmzasz commented
its not a "fear" its a principle, why install more and more software to do tasks that the currently installed software can already handle just fine.

2022-04-28 19:26 UTC, tmzasz commented
theres also the issue of slowly creeping into Dependency hell for nothing

2022-05-06 10:00 UTC, Legrems commented
"Creeing into dependency hell for nothing"
Ok, then don't install factorio-init (which by the way don't work atm, so nice dependancy) to "just" install a server because it's still one more dependances than just downloading and launching the game.

2022-05-06 15:07 UTC, Legrems commented
Just before definetly closing this, i'm curious to know your opinion on this @Bisa.

Thank's in advance !

2022-08-21 20:56 UTC, Bisa commented
Thnx for the suggested fix @Legrems - I did however opt to use already existing tools, at some point in the future I may look at using the api, but much like @tmzasz I try to stick to as few "extras" as I can (when I remember to and when I do not whirr off into some random "this is so cool" spree ;) )

2022-08-21 20:56 UTC, closed without merging